server:
  port: 8888

spring:
  redis:
    url: 192.168.181.128:6379

  rabbitmq:
    host: localhost
    password: guest
    username: guest
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual